#!/usr/bin/env python2
from briareos.zbroker import ZBroker
from briareos.utils import logger
from briareos.common import VERSION

import sys
import signal

INFO = "Briareos Z-Broker"


def run_forever():
    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    while True:
        signal.pause()


def stop(sig, frame):
    zbroker.stop()
    logger.success("Done")
    sys.exit(0)


if __name__ == "__main__":
    logger.banner(INFO, VERSION)

    # TODO argparse
    if len(sys.argv) > 1:
        zbroker = ZBroker(sys.argv[1])
    else:
        zbroker = ZBroker()

    zbroker.start()
    run_forever()
